# CompSci 169 - Optimization <br> Homework 3
## Hector G. Flores Rodriguez (Id. 25721714)

### 1. Unconstrained minimization of multivariate Rosenbrock function.<sup>[1](#scipy1)</sup>

To demonstrate SciPy's [minimize](https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.minimize.html#scipy.optimize.minimize) in [scipy.optimize](https://docs.scipy.org/doc/scipy/reference/optimize.html#module-scipy.optimize), we will consider minimizing the multivariate generalization of the [Rosenbrock function](https://en.wikipedia.org/wiki/Rosenbrock_function) defined as:

$$
f(\mathbf{x}) = \sum_{i=1}^{N-1} [100(x_{i+1} - x_{i}^{2})^2 + (1 - x_{i})^2] \;, \quad \text{where} \space \mathbf{x} \in \mathbb{R}^N
$$

This variant has a minimum at $x_{i}^{*} = 1$, for $i=1,\ldots ,N$

<br>

#### References
<a name="scipy1">1</a>: ["Generalized Rosenbrock's function"](https://docs.scipy.org/doc/scipy/reference/tutorial/optimize.html). Retrieved 2008-09-16.

<a name="rosen">2</a>: H. H. Rosenbrock; An Automatic Method for Finding the Greatest or Least Value of a Function, The Computer Journal, Volume 3, Issue 3, 1 January 1960, Pages 175–184, https://doi.org/10.1093/comjnl/3.3.175

In [1]:
%matplotlib inline

In [2]:
import numpy as np
from scipy.optimize import minimize

In [3]:
def rosen(x):
    """The Rosenbrock function.
    
    Reference:
        https://docs.scipy.org/doc/scipy/reference/tutorial/optimize.html
    """
    return sum(100.0*(x[1:] - x[:-1]**2.0)**2.0 + (1 - x[:-1])**2.0)

In [4]:
np.random.seed(13)
mu, sigma = 1, 2
x0 = np.random.normal(mu, sigma, size=(10,))  # N=10 for Rosenbrock function
x0

array([-0.42478132,  2.50753276,  0.91099384,  1.90362468,  3.69020342,
        2.06467578,  3.7003758 ,  2.72242275,  3.95737147, -1.09075426])

In [5]:
# The minimize routine is used with Nelder-Mead simplex algorithm
# Reference: https://docs.scipy.org/doc/scipy/reference/tutorial/optimize.html
res = minimize(rosen, x0, method='nelder-mead', options={'xtol': 1e-8, 'disp': True})
res.x

array([ -1.17067668,   1.15723268,   1.12073321,   1.1122073 ,
         1.12125056,   1.19744898,   1.37010315,   1.84298227,
         3.40519087,  11.59507507])

For further demonstration we will paramerterize the rosenbrock function defined above, such that we can vary constants $a$ and $b$. The multivariate Rosenbrock function is now defined to be:

$$
f(\mathbf{x}) = \sum_{i=1}^{N-1} [b(x_{i+1} - x_{i}^{2})^2 + (a - x_{i})^2] \;, \quad \text{where} \space \mathbf{x} \in \mathbb{R}^N \: \text{and } \space a, \;b \in \mathbb{R}
$$

In [6]:
def rosen_param(x, a, b):
    """The Rosenbrock function.
    
    Reference:
        https://docs.scipy.org/doc/scipy/reference/tutorial/optimize.html
    """
    return sum(b*(x[1:] - x[:-1]**2.0)**2.0 + (a - x[:-1])**2.0)

In [7]:
np.random.seed(13)
a = np.random.randint(1, 10)                   # Randomly pick a from interval [1, 10]
b = np.random.randint(10, 200)                 # Randomly pick b from interval [10, 200]
mu, sigma = a, 4                               # 
xx0 = np.random.normal(mu, sigma, size=(10,))  # N=10 for Rosenbrock function

print("xx0: {}".format(np.array_str(xx0, precision=2)), 
      "a: {}".format(a), 
      "b: {}".format(b), sep='\n')

xx0: [  5.65   0.86  11.83  -0.77   5.53   7.92   1.74   2.43   1.59   6.97]
a: 3
b: 186


In [8]:
# The minimize routine is used with Nelder-Mead simplex algorithm
# Reference: https://docs.scipy.org/doc/scipy/reference/tutorial/optimize.html
res2 = minimize(rosen_param, xx0, args=(a, b), method='nelder-mead', options={'xtol': 1e-100, 'disp': True})
res2.x

array([ -7.37875061e-01,   7.10982450e-01,   5.95803535e-01,
         2.93032220e-01,   1.75710761e-01,   9.96809838e-03,
        -1.22131945e+00,   1.93623025e+00,   3.88950296e+00,
         1.49176282e+01])